---
#
# Ansible managed
#
repository:
  description: Manage firewall ports on all (known) Linux operating systems.
  homepage: https://robertdebock.nl/
  topics: firewall, firewalld, server, system, security, ansible, molecule, playbook
